version: 2
jobs:
   build:
     docker:
       - image: circleci/node:7
     steps:
       - checkout
       - run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile /dev/null -v $DROPLET_USER@$DROPLET_IP ./deploy.sh
