version: 2
jobs:
  build-job:
    docker:
      - image: ubuntu
    working_directory: /tmp/quotes-db-mongo
    steps:
      - run: echo "Running quotes-db-mongo"

  deploy-job:
    docker:
      - image: quotes-db-mongo
    working_directory: /tmp/quotes-db-mongo
    steps:
      - run:
          name: Spin up db
          command: ./run.sh

workflows:
  version: 2
    deploy:
      jobs:
        - build-job
        - deploy-job
                  